### ISSUE TITLE
Cannot find module './arrayWithHoles.js'

### ISSUE THREAD

**Issue by frenicohansen** [atlassian/pragmatic-drag-and-drop#81]
## Issue Summary

I encountered an error while trying to port the pragmatic drag and drop React version example [pdnd-react-tailwind](https://github.com/alexreardon/pdnd-react-tailwind) into a Vue version using the Nuxt framework.

## Error Details

I received the following error in this reproduction: [Error Reproduction](https://codesandbox.io/p/devbox/pnd-nuxt-error-sxxyp3).

```
Cannot find module './arrayWithHoles.js' Require stack: - /project/workspace/@babel/runtime/helpers/slicedToArray

at Module._load (node:internal/modules/cjs/loader:901:27)
at Module.require (node:internal/modules/cjs/loader:1115:19)
at require (node:internal/modules/helpers:130:18)
at ./@babel/runtime/helpers/slicedToArray:1:22
at ViteNodeRunner.runModule (./node_modules/.pnpm/vite-node@1.6.0/node_modules/vite-node/dist/client.mjs:362:11)
at ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@1.6.0/node_modules/vite-node/dist/client.mjs:346:16)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@1.6.0/node_modules/vite-node/dist/client.mjs:189:14)
at async ViteNodeRunner.dependencyRequest (./node_modules/.pnpm/vite-node@1.6.0/node_modules/vite-node/dist/client.mjs:233:12)
```

However, in another reproduction, it works fine: [Working Reproduction](https://codesandbox.io/p/devbox/pnd-nuxt-working-pwrx9w). 

Any help in resolving this issue would be greatly appreciated. Thank you!

## Suspected Cause

I believe the issue might be related to differences in the `pnpm-lock.yaml` file content between the two reproductions. Everything else appears to be identical.

## Steps to Reproduce

1. Open the reproduction.
2. Install dependencies using `pnpm install`.
3. Run the Nuxt application using `pnpm dev`.

## Environment
```
  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 321.55 MB / 4.01 GB
    Container: Yes
    Shell: Unknown
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    nuxt: ^3.12.2 => 3.12.2 
    vue: latest => 3.4.31 
```

**Comment by alexreardon** [comment]
I am confused by this one. We have no file in library or example source called `arrayWithHoles`

**Comment by alexreardon** [comment]
Sounds like an issue with babel / webpack https://github.com/webpack/webpack/issues/11467
